update breakup

diff --git a/bin/breakup b/bin/breakup
--- a/bin/breakup
+++ b/bin/breakup
@@ -1,5 +1,11 @@
 #!/usr/bin/env bash
+# Breakup a file into 500m chunks
 
 FILE="$1"
 
-split -b 500m --numeric-suffixes $FILE $FILE.
+if [ ! -f $FILE ]; then
+  echo "Could not find $FILE"
+  exit 1
+else
+  split -b 500m --numeric-suffixes $FILE $FILE.
+fi
