update syncnow

diff --git a/bin/syncnow b/bin/syncnow
--- a/bin/syncnow
+++ b/bin/syncnow
@@ -1,4 +1,16 @@
 #!/usr/bin/env bash
-# Sync now
+# Sync with osync
+# Makes sure script and config is installed
 
-~/.rep/osync/osync.sh ~/.config/osync/sync.conf --summary
+SYNC_SCRIPT="$HOME/.rep/osync/osync.sh"
+SYNC_CONFIG="$HOME/.config/osync/sync.conf"
+
+if [ ! -f $SYNC_SCRIPT ]; then
+  echo "Could not find sync script ($SYNC_SCRIPT missing)"
+  exit 1
+elif [ ! -f $SYNC_CONFIG ]; then
+  echo "Could not find sync config ($SYNC_CONFIG missing)"
+  exit 2
+else
+  $SYNC_SCRIPT $SYNC_CONFIG --summary
+fi
